config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: %i[show edit update] do
    resources :teams, only: %i[new create index]
    resources :boards, shallow: true
  end
  delete 'end_trial/:id', to: 'users#end_trial'
  post 'toggle-random-message', to: 'users#toggle_random_message'
  post 'set_plan', to: 'users#set_plan'
  post 'toggle-user-block/:id', to: 'users#toggle_user_block'
  post 'toggle-board-delete-emails/:id', to: 'users#toggle_board_delete_emails'
  post 'toggle-board-update-emails/:id', to: 'users#toggle_board_update_emails'
  post 'toggle-board-create-emails/:id', to: 'users#toggle_board_create_emails'
  root 'pages#home'
  get 'our-plans', to: 'pages#plans'
  get 'payment-block', to: 'pages#payment_block'
  get 'trial-block', to: 'pages#trial_block'
  get 'user-block', to: 'pages#user_block'

  resources :plans
  resources :boards, except: %i[index new create] do
    resources :task_lists, shallow: true do
      resources :tasks, only: %i[new index create]
    end
  end
  post 'toggle_board_visibility/:id', to: 'boards#toggle_visibility'

  resources :tasks, only: %i[show edit update destroy]
  get 'complete_task/:id', to: 'tasks#complete_task'
  post 'complete_task/:id', to: 'tasks#complete_task_action'

  resources :task_users, only: %i[create destroy]

  get 'admin', to: 'admins#admin_menu'

  resources :payments, only: %i[create new]

  resources :white_lists, only: [:index, :destroy, :create]
end

app/models/Task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :task_list
  has_rich_text :content
  has_many :task_change_records
  before_update :add_change_record if :will_save_change_to_task_list_id?
  after_create :add_change_record_on_create
  has_many :task_users
  has_many :users, through: :task_users

  delegate :board, to: :task_list

  def add_change_record
    TaskChangeRecord.create(new_list: task_list.title, task: self) unless task_list_id == task_list_id_was
  end

  def add_change_record_on_create
    TaskChangeRecord.create(new_list: task_list.title, task: self)
  end

  def doing_time_hours
    return nil unless doing_time

    doing_time / 1.hour
  end

  def has_auth_to_update?(user)
    return true if creator == user

    board.author == user
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  authorize_persona class_name: 'User'
  grant(
    user: :all,
    manager: :all
  )
  before_action :block_access_to_admin
  before_action :set_task_list, only: %i[new create index]
  before_action :set_task, except: %i[new create index]
  before_action :valid_task_incompleted, only: [:complete_task]
  before_action :validate_task_list, only: %i[new create index]
  before_action :validate_task, except: %i[new create index]
  before_action :validate_task_auth, only: %i[edit update complete complete_task_action]

  def index
    @tasks = @task_list.tasks
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.creator = current_user
    if @task.save
      flash[:notice] = 'Task saved successfully'
      redirect_to board_path(@task_list.board)
    else
      flash.now[:alert] = 'There was an error on saving the task'
      render 'new'
    end
  end

  def edit; end

  def update
    Task.transaction do
      @task.update(task_params)
    end
    flash[:notice] = 'Task updated successfully'
    redirect_to board_path(@task.board)
  rescue StandardError
    flash[:alert] = 'There was an error'
    render 'edit'
  end

  def destroy
    if @task.destroy
      flash[:notice] = 'Task was deleted successfully'
    else
      flash[:alert] = 'There was an error deleting the task'
    end

    redirect_to task_list_path(@task.task_list)
  end

  def complete_task; end

  def complete_task_action
    Task.transaction do
      @task.update(complete_task_params)
      doing_time = (@task.finished_at - @task.started_at).to_i
      @task.update(doing_time: doing_time)
      @task.update(completed: true)
    end

    flash[:notice] = 'Task mark as completed'
    redirect_to board_path(@task.board)
  rescue ActiveRecord::ActiveRecordError
    flash.now[:alert] = 'There was an error'
    render complete_task
  end

  private

  def validate_task_auth
    unless @task.has_auth_to_update?(current_user)
      flash[:alert] = 'You do not have access to perform this action'
      redirect_back(fallback_location: root_path)
    end
  end

  def set_task_list
    @task_list = TaskList.find_by(id: params[:task_list_id])
  end

  def task_params
    params.require(:task).permit(:title, :task_id, :content, :task_list_id)
  end

  def complete_task_params
    params.permit(:started_at, :finished_at, :justification, :task_list_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def valid_task_incompleted # good managing all case scenarios
    if @task.completed
      flash[:alert] = 'That task is already completed'
      redirect_to task_path(@task)
    end
  end

  def validate_task_list # authorization_persona
    unless current_user.is_manager_or_manager_team?(@task_list.board.author)
      flash[:alert] = 'You cannot access this task list'
      redirect_back(fallback_location: root_path)
    end
  end

  def validate_task # this should have been managed by authorization persona
    unless current_user.is_manager_or_manager_team?(@task.task_list.board.author)
      flash[:alert] = 'You cannot access this task'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/task_helper.rb
# frozen_string_literal: true

module TaskHelper
  def task_new_header
    { title: 'Tasks',
      text: 'Create a new task and start working on it.',
      config: true }
  end

  def task_edit_header
    { title: 'Tasks',
      text: 'Edit a task',
      config: true }
  end

  def task_index_header(task_list)
    { title: 'Tasks',
      text: "You are watching all the tasks from #{task_list.title} list",
      config: true }
  end

  def task_form_models
    @task&.id.nil? ? [@task_list, @task] : [@task]
  end

  def task_form_task_lists
    @task&.id.nil? ? @task_list.board.task_lists : @task.board.task_lists
  end

  def task_complete_page_header
    { title: 'Complete task',
      text: 'Set task as completed',
      config: true }
  end

  def task_show_page_header
    { title: 'Task',
      text: 'See details of task',
      config: true }
  end

  def task_user_id_from_user_task(user, task)
    TaskUser.find_by(user: user, task: task).id
  end

  def board_task_label_title(task)
    task.completed ? 'Finished' : 'Incomplete'
  end

  def board_task_label_style(task)
    task.completed ? 'bg-success' : 'bg-secondary'
  end
end

app/views/tasks/_add_user_form.html.erb
<div class="card">
    <div class="card-header">
        <p class="m-0">Add User</p>
    </div>
    <div class="card-body">
        <%= form_with url: '/task_users', method: :post do |form| %>
            <%= hidden_field_tag :task_id, @task.id %>
            <div class="form-group mb-3">
                <%= form.label :Email %>
                <%= form.text_field :email, class: 'form-control' %>
            </div>

            <div class="d-flex justify-content-end">
                <%= form.submit 'Add', class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: task_form_models do |form| %>
    <div class="form-group mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: 'form-control', placeholder: 'Enter a title' %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :task_list_id%>
        <%= form.collection_select :task_list_id,
                        task_form_task_lists,
                        :id,
                        :title,
                        {},
                        class: 'form-control' %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
    </div>

    <div class="d-flex justify-content-end mt-5">
        <%= link_to 'Return', :back, class: 'btn btn-primary me-2' %>
        <%= form.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<% presenter = TaskPresenter.new(task) %>

<div class="card mb-4">
  <div class="card-header">
    Task
  </div>
  <div class="card-body">
    <h5 class="text-start"><span class="badge <%= board_task_label_style(task) %>"><%= board_task_label_title(task) %></span></h5>
    <h5 class="card-title mb-3"><%= task.title %> Task</h5>
    <p class="m-0 mb-1">
        <strong>Task List: </strong>
        <%= task.task_list.title %>
    </p>
    <p class="m-0 mb-1">
        <strong>Author: </strong>
        <%= task.creator.full_name %>
    </p>

    <% if task.completed %>
      <p class="m-0 mb-1">
        <strong>Started at: </strong>
        <%= presenter.readable_started_date %>
      </p>

      <p class="m-0 mb-1">
        <strong>Finished at: </strong>
        <%= presenter.readable_finished_date %>
      </p>

      <p class="m-0 mb-1">
        <strong>Doing time: </strong>
        <%= presenter.readable_doing_time %>
      </p>

      <p class="m-0 mb-1">
        <strong>Justification: </strong>
        <%= task.justification %>
      </p>
    <% end %>

    
    <% unless task.content.blank? %>
      <p><strong>Content: </strong></p>
      <hr>
      <p><%= task.content %></p>
    <% end %>

    <div class="d-flex justify-content-end">
        <%= link_to 'Delete',
                    task_path(task),
                    method: :delete,
                    class: 'btn btn-danger me-2',
                    data: {confirm: "Do you really want to delete"} %>
        <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-warning block option-btn' %>
        <% unless request.path == task_path(task) %>
          <%= link_to 'See task', task_path(task), class: 'btn btn-primary ms-2' %>
        <% end %>
    </div>

    <% if !task.completed %>
      <hr>
      <div class="d-flex justify-content-end">
        <%= link_to 'Mark as completed', "/complete_task/#{task.id}", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_task_records_list.html.erb
<div class="card">
    <div class="card-header">
        Change Records
    </div>
    <div class="card-body">
        <% records.each do |record| %>
            <div class="bg-light py-3 px-3 rounded mb-3">
                <div class="d-flex justify-content-between">
                    <p class="m-0"><%= record.new_list %></p>
                    <p class="m-0"><%= record.date.strftime("%d/%m/%y - %H:%M") %></p>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/_users_assigned.html.erb
<div class="card">
    <div class="card-header">
        <p class="m-0">Users assigned</p>
    </div>
    <div class="card-body">
        <% if @task.users.count == 0 %>
            <div class="bg-light py-3 px-3 rounded mb-3">
                <p class="h3 text-center">There are no users assigned</p>
            </div>
        <% end %>

        <% @task.users.each do |user| %>
            <div class="bg-light py-3 px-3 rounded mb-3">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <p class="m-0"><%= user.full_name %></p>
                        <p class="m-0"><%= user.email %></p>
                    </div>
                    <div>
                        <%= link_to 'delete',
                                    task_user_path(task_user_id_from_user_task(user, @task)),
                                    class: 'btn btn-danger me-2',
                                    data: {confirm: "Do you really want to delete"},
                                    method: :delete %>
                        <%= link_to 'see', user_path(user), class: 'btn btn-primary' %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/complete_task.html.erb
<div class="container">
    <%= render 'pg_header', task_complete_page_header %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">Task</p>
                <p class="m-0"><%= @task.title %></p>
            </div>
            <%= link_to 'Return', :back, class: 'btn btn-primary' %>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            
            <%= form_with url: "/complete_task/#{@task.id}", method: :post do |form| %>
                <div class="form-group mb-3">
                    <%= form.label :Justification %>
                    <%= form.text_field :justification, class: 'form-control' %>
                </div>

                <div class="form-group mb-3">
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <%= form.label :started_at %>
                            <%= datetime_field_tag :started_at, Time.zone.now.strftime("%Y-%m-%dT00:00:00"), class: 'form-control', min: Date.today %>
                        </div>

                        <div class="col-12 col-md-6">
                            <%= form.label :finished_at %>
                            <%= datetime_field_tag :finished_at, Time.zone.now.strftime("%Y-%m-%dT00:00:00"), class: 'form-control', min: Date.today %>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-3">
                    <%= form.label :task_list_id%>
                    <%= select_tag :task_list_id, options_from_collection_for_select(@task.board.task_lists, 'id', 'title'), class: 'form-control' %>
                </div>

                <div class="d-flex justify-content-end mt-5">
                    <%= link_to 'Return', :back, class: 'btn btn-primary me-2' %>
                    <%= form.submit 'Complete', class: 'btn btn-success' %>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
    <%= render 'pg_header', task_new_header %>

    <%= render 'model_errors', obj: @task %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container mb-5">
    <%= render 'pg_header', task_index_header(@task_list) %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">Task list:</p>
                <p class="m-0"><%= @task_list.title %></p>
            </div>
            <div>
                <%= link_to 'Go to board', board_path(@task_list.board), class: 'btn btn-primary ma-2' %>
                <%= link_to 'Create task', new_task_list_task_path(@task_list), class: 'btn btn-success' %>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
         <% @tasks.each do |task| %>
            <div class="col-12 col-lg-8">
                <%= render 'task', task: task %>
            </div>
        <% end %>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
    <%= render 'pg_header', task_new_header %>

    <%= render 'model_errors', obj: @task %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<div class="container mb-5">
    <%= render 'pg_header', task_show_page_header %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">Task</p>
                <p class="m-0"><%= @task.title %></p>
            </div>
            <div>
                <%= link_to 'Return to task lists',
                            board_task_lists_path(@task.board),
                            class: 'btn btn-primary' %>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-8">
            <%= render 'task', task: @task %>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-2">
        <div class="col-12 col-lg-8">
            <%= render 'task_records_list', records: @task.task_change_records %>
        </div>
    </div>

    <div class="mt-5 text-center">
        <h2>Users</h2>
        <hr class="mb-5">
    </div>

    <div class="row d-flex justify-content-center mt-2">
        <div class="col-12 col-lg-8">
            <%= render 'add_user_form' %>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-4">
        <div class="col-12 col-lg-8">
            <%= render 'users_assigned' %>
        </div>
    </div>
</div>