config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: %i[show edit update] do
    resources :teams, only: %i[new create index]
    resources :boards, shallow: true
  end
  delete 'end_trial/:id', to: 'users#end_trial'
  post 'toggle-random-message', to: 'users#toggle_random_message'
  post 'set_plan', to: 'users#set_plan'
  post 'toggle-user-block/:id', to: 'users#toggle_user_block'
  post 'toggle-board-delete-emails/:id', to: 'users#toggle_board_delete_emails'
  post 'toggle-board-update-emails/:id', to: 'users#toggle_board_update_emails'
  post 'toggle-board-create-emails/:id', to: 'users#toggle_board_create_emails'
  root 'pages#home'
  get 'our-plans', to: 'pages#plans'
  get 'payment-block', to: 'pages#payment_block'
  get 'trial-block', to: 'pages#trial_block'
  get 'user-block', to: 'pages#user_block'

  resources :plans
  resources :boards, except: %i[index new create] do
    resources :task_lists, shallow: true do
      resources :tasks, only: %i[new index create]
    end
  end
  post 'toggle_board_visibility/:id', to: 'boards#toggle_visibility'

  resources :tasks, only: %i[show edit update destroy]
  get 'complete_task/:id', to: 'tasks#complete_task'
  post 'complete_task/:id', to: 'tasks#complete_task_action'

  resources :task_users, only: %i[create destroy]

  get 'admin', to: 'admins#admin_menu'

  resources :payments, only: %i[create new]

  resources :white_lists, only: [:index, :destroy, :create]
end

app/models/task_list.rb
# frozen_string_literal: true

class TaskList < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
  alias_attribute :title, :name
  validate :board_list_capacity

  def board_list_capacity
    if board.max_task_lists_reached?
      errors.add(:board_id, "Board cannot have more than #{Board.TASK_LIST_LIMIT} task lists")
    end
  end
end

app/controllers/task_lists_controller.rb
# frozen_string_literal: true

class TaskListsController < ApplicationController
  authorize_persona class_name: 'User'
  grant(
    user: :all,
    manager: :all
  )

  before_action :block_access_to_admin # this should have been done through authorization_persona
  before_action :set_board_from_url_param, only: %i[new index create]
  before_action :set_task_list, except: %i[index new create]

  # a lot of validations here
  before_action :validate_board_url_param_id, only: %i[new index create]
  before_action :validate_board_param, only: [:create]

  before_action :validate_task_list, only: %i[edit update destroy show]

  def index
    @task_lists = @board.task_lists
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show; end

  def new
    @task_list = TaskList.new
  end

  def create
    @task_list = TaskList.new(task_list_params)
    @task_list.board_id = @board.id
    if @task_list.save
      flash[:notice] = 'Task list created'
      redirect_to board_path(@task_list.board)
    else
      flash.now[:alert] = 'There was an error'
      render 'new'
    end
  end

  def destroy
    if @task_list.destroy
      flash[:notice] = 'Task list was destroyed successfuly'
    else
      flash[:alert] = 'There was an error on deleting the task list'
    end
    redirect_to board_task_lists_path(@task_list.board)
  end

  def edit; end

  def update
    if @task_list.update(task_list_params)
      flash[:notice] = 'Task list was updated successfully'
      redirect_to board_task_lists_path(@task_list.board)
    else
      flash.now[:alert] = 'There was an error'
      render 'edit'
    end
  end

  private

  # again, the following two methods are just
  # the same but named differently
  def validate_board_url_param_id
    unless valid_board?(params[:board_id])
      flash[:alert] = 'The board you are trying to access is not valid'
      redirect_to board_index_path(current_user)
    end
  end

  def validate_board_param # this could have done through halting with an exception rescue 
    # rescue_from at the beginning, while doing a board.find() and if it throws an error
    # you would have been able to catch it with the rescue_from 
    # and the method could redirect_back with the alert
    unless valid_board?(params[:board_id])
      flash[:alert] = 'The board you are trying to access is not valid'
      redirect_to board_index_path(current_user)
    end
  end

  def valid_board?(id)
    board = Board.find_by(id: id)
    return false unless board # something like this

    current_user.is_manager_or_manager_team?(board.author)
  end

  def task_list_params
    params.require(:task_list).permit(:name, :color, :priority, :board_id)
  end

  def set_board_from_url_param
    @board = Board.find(params[:board_id])
  end

  def set_task_list
    @task_list = TaskList.find(params[:id])
  end

  def validate_task_list
    unless current_user.is_manager_or_manager_team?(@task_list.board.author)
      flash[:alert] = 'You cannot access that task list'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/task_list_helper.rb
# frozen_string_literal: true

module TaskListHelper
  def task_list_new_header
    { title: 'Task list creator',
      text: 'Create a new list to organize better your tasks.',
      config: true }
  end

  def task_list_index_header(board)
    { title: 'Task lists',
      text: "You are watching task lists from '#{board.title}' board",
      config: true }
  end
end

app/views/task_lists/_form.html.erb
<%= form_with model: [@board, @task_list] do |form| %>
    <div class="row">
        <div class="form-group mb-3 col-12 col-md-6">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control', placeholder: 'Enter a name for your list' %>
        </div>

        <div class="form-group mb-3 col-12 col-md-6">
            <%= form.label :priority %>
            <%= form.number_field :priority, class: 'form-control', placeholder: 'Enter a priority for your list',in: 1..10000, step: 1 %>
        </div>

        <div class="form-group mb-3 col-12 col-md-6">
            <%= form.label :color %>
            <%= form.color_field :color, class: 'form-control p-0 cl-picker' %>
        </div>
    </div>

    <div class="d-flex justify-content-end mt-5">
        <%= link_to 'Return', :back, class: 'btn btn-primary me-2' %>
        <%= form.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/task_lists/_task_list.html.erb
<div class="card mb-4">
  <div class="card-header">
    Task list
  </div>
  <div class="card-body">
    <h5 class="card-title mb-3"><%= task_list.title %> list</h5>
    <p class="m-0 mb-1">
        <strong>Color: </strong>
        <%= task_list.color %>
        <span class="h5 p-0 m-0" style="color: <%= task_list.color %>">■</span> 
    </p>
    <p class="m-0 mb-1"><strong>Priority: </strong><%= task_list.priority %></p>
    <div class="d-flex justify-content-end">
        <%= link_to 'Delete',
                    task_list_path(task_list),
                    method: :delete, 
                    class: 'btn btn-danger block option-btn me-2',
                    data: {confirm: "Do you really want to delete" }
                    %>
        <%= link_to 'Edit', edit_task_list_path(task_list), class: 'btn btn-warning block option-btn' %>
        <% unless request.path == task_list_path(task_list) %>
          <%= link_to 'See', task_list_path(task_list), class: 'btn btn-primary block option-btn ms-2' %>
        <% end %>
    </div>
    <hr>
    <div class="d-flex justify-content-end">
        <%= link_to 'See tasks', task_list_tasks_path(task_list), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/task_lists/edit.html.erb
<div class="container">
    <%= render 'pg_header', task_list_new_header %>

    <%= render 'model_errors', obj: @task_list %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%=render 'form' %>
        </div>
    </div>
</div>

app/views/task_lists/index.html.erb
<div class="container mb-5">
    <%= render 'pg_header', task_list_index_header(@board) %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">User</p>
                <p class="m-0"><%= current_user.full_name %></p>
            </div>
            <div>
                <%= link_to 'Go to board', board_path(@board), class: 'btn btn-primary ma-2' %>
                <%= link_to 'Create task list', new_board_task_list_path(@board), class: 'btn btn-success' %>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <% @task_lists.each do |task_list| %>
            <div class="col-12 col-lg-8">
                <%= render 'task_list', task_list: task_list %>
            </div>
        <% end %>
    </div>
</div>

app/views/task_lists/new.html.erb
<div class="container">
    <%= render 'pg_header', task_list_new_header %>

    <%= render 'model_errors', obj: @task_list %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/task_lists/show.html.erb
<% presenter = TaskListPresenter.new(@task_list) %>

<div class="container mb-5">
    <%= render 'pg_header', presenter.show_page_header %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">User</p>
                <p class="m-0"><%= current_user.full_name %></p>
            </div>
            <div>
                <%= link_to 'Return to task lists', board_task_lists_path(@task_list.board), class: 'btn btn-primary' %>
                <%= link_to 'Create task', new_task_list_task_path(@task_list), class: 'btn btn-success' %>
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-8">
            <%= render 'task_list', task_list: @task_list %>
        </div>
    </div>
</div>