config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: %i[show edit update] do
    resources :teams, only: %i[new create index]
    resources :boards, shallow: true
  end
  delete 'end_trial/:id', to: 'users#end_trial'
  post 'toggle-random-message', to: 'users#toggle_random_message'
  post 'set_plan', to: 'users#set_plan'
  post 'toggle-user-block/:id', to: 'users#toggle_user_block'
  post 'toggle-board-delete-emails/:id', to: 'users#toggle_board_delete_emails'
  post 'toggle-board-update-emails/:id', to: 'users#toggle_board_update_emails'
  post 'toggle-board-create-emails/:id', to: 'users#toggle_board_create_emails'
  root 'pages#home'
  get 'our-plans', to: 'pages#plans'
  get 'payment-block', to: 'pages#payment_block'
  get 'trial-block', to: 'pages#trial_block'
  get 'user-block', to: 'pages#user_block'

  resources :plans
  resources :boards, except: %i[index new create] do
    resources :task_lists, shallow: true do
      resources :tasks, only: %i[new index create]
    end
  end
  post 'toggle_board_visibility/:id', to: 'boards#toggle_visibility'

  resources :tasks, only: %i[show edit update destroy]
  get 'complete_task/:id', to: 'tasks#complete_task'
  post 'complete_task/:id', to: 'tasks#complete_task_action'

  resources :task_users, only: %i[create destroy]

  get 'admin', to: 'admins#admin_menu'

  resources :payments, only: %i[create new]

  resources :white_lists, only: [:index, :destroy, :create]
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  default_scope { order(:plan_id) }
  monetize :price_cents
  has_many :users

  def duration_in_days
    time_months.months.days
  end
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

class PlansController < ApplicationController
  authorize_persona class_name: 'User'
  grant(
    admin: :all
  )
  before_action :set_plan, only: %i[edit update destroy show]

  def index
    @plans = Plan.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show; end

  def edit; end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      flash[:notice] = 'Plan was create successfully'
      redirect_to plans_path
    else
      flash.now[:alert] = 'There was an error'
      render 'new'
    end
  end

  def update
    if @plan.update(plan_params)
      flash[:notice] = 'The plan was successfully updated'
      redirect_to plans_path
    else
      flash.now[:error] = 'There was an error'
      render 'update'
    end
  end

  def destroy
    if Plan.where(plan_id: @plan.id).joins(:users).count != 0
      flash[:alert] = 'You can not delete a plan while it has users in it.'
      redirect_to plans_path
      return
    end

    if @plan.destroy
      flash[:notice] = 'The plan was successfully deleted'
    else
      flash[:alert] = 'There was an error'
    end
    redirect_to plans_path
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:title, :member_quantity, :price, :time_months)
  end
end

app/helpers/plan_helper.rb
# frozen_string_literal: true

module PlanHelper
  def index_header
    { title: 'Prices and Plans',
      text: 'Edit plan data like price and users allowed.',
      config: true }
  end

  def plan_new_header
    { title: 'Create plan',
      text: 'Create a new plan for your users.',
      config: true }
  end

  def user_plans_header
    { title: 'Prices and plans',
      text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus quos quisquam molestiae quo commodi beatae cum debitis natus nihil repudiandae.' }
  end

  def plan_info_to_show(plan)
    { title: plan.title,
      price: plan.price.to_s,
      time_months: plan.time_months,
      member_quantity: plan.member_quantity }
  end
end

app/views/plans/_form.html.erb
<%= form_with model: @plan do |form| %>
    <div class="form-group mb-3">
        <%= form.label :title%>
        <%= form.text_field :title, class: 'form-control', placeholder: 'Enter a title' %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :price%>
        <%= form.number_field :price, class: 'form-control', placeholder: 'Enter a price', in: 1.0..10000.0, step: 0.01 %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :member_quantity%>
        <%= form.number_field :member_quantity, class: 'form-control', placeholder: 'Enter a member quantity', in: 1..10000 %>
    </div>

    <div class="form-group mb-3">
        <%= form.label :time_months%>
        <%= form.number_field :time_months, class: 'form-control', placeholder: 'Enter a renewal time in months', in: 1..256 %>
    </div>

    <div class="d-flex justify-content-end mt-5">
        <%= link_to plans_path  do %>
            <button class='btn btn-primary me-2'>Return</button>
        <% end %>
        <%= form.submit class: 'btn btn-success' %>
    </div>
<% end %>

app/views/plans/_plan_card.html.erb
<div class="card mb-4">
  <div class="card-header">
    Plan and prices
  </div>
  <div class="card-body">
    <h5 class="card-title mb-3"><%= plan.title %> plan</h5>
    <p class="m-0 mb-1"><strong>Price: </strong><%= plan.price %> $</p>
    <p class="m-0 mb-1"><strong>User quantity: </strong><%= plan.member_quantity %> users</p>
    <p class="m-0 mb-1"><strong>Renew time: </strong><%= plan.time_months %> months</p>
    <div class="d-flex justify-content-end">
        <%= link_to 'Delete',
                    plan_path(plan),
                    method: :delete, 
                    class: 'btn btn-danger block option-btn me-2',
                    data: {confirm: "Do you really want to delete" }
                    %>
        <%= link_to 'Edit', edit_plan_path(plan), class: 'btn btn-warning block option-btn' %>
    </div>
  </div>
</div>

app/views/plans/edit.html.erb
<% presenter = PlanPresenter.new(@plan) %>

<div class="container mb-5">
    <%= render 'pg_header', presenter.edit_page_header %>

    <%= render 'model_errors', obj: @plan %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/plans/index.html.erb
<div class="container mb-5">
    <%= render 'pg_header', index_header %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">User</p>
                <p class="m-0"><%= current_user.full_name %></p>
            </div>
            <%= link_to 'Create Plan', new_plan_path, class: 'btn btn-success' %>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <% @plans.each do |plan| %>
            <div class="col-12 col-lg-8">
                <%= render 'plan_card', plan: plan %>
            </div>
        <% end %>
    </div>
</div>

app/views/plans/new.html.erb
<% presenter = PlanPresenter.new(@plan) %>

<div class="container mb-5">
    <%= render 'pg_header', plan_new_header %>

    <%= render 'model_errors', obj: @plan %>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-7">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/plans/show.html.erb
<div class="container mb-5">
    <%= render 'pg_header', index_header %>

    <div class="bg-dark rounded p-4 my-4 text-white">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <p class="h5 m-0">User</p>
                <p class="m-0"><%= current_user.full_name %></p>
            </div>
            <%= link_to 'Return to plans', plans_path, class: 'btn btn-primary' %>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-8">
            <%= render 'plan_card', plan: @plan %>
        </div>
    </div>
</div>