config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: %i[show edit update] do
    resources :teams, only: %i[new create index]
    resources :boards, shallow: true
  end
  delete 'end_trial/:id', to: 'users#end_trial'
  post 'toggle-random-message', to: 'users#toggle_random_message'
  post 'set_plan', to: 'users#set_plan'
  post 'toggle-user-block/:id', to: 'users#toggle_user_block'
  post 'toggle-board-delete-emails/:id', to: 'users#toggle_board_delete_emails'
  post 'toggle-board-update-emails/:id', to: 'users#toggle_board_update_emails'
  post 'toggle-board-create-emails/:id', to: 'users#toggle_board_create_emails'
  root 'pages#home'
  get 'our-plans', to: 'pages#plans'
  get 'payment-block', to: 'pages#payment_block'
  get 'trial-block', to: 'pages#trial_block'
  get 'user-block', to: 'pages#user_block'

  resources :plans
  resources :boards, except: %i[index new create] do
    resources :task_lists, shallow: true do
      resources :tasks, only: %i[new index create]
    end
  end
  post 'toggle_board_visibility/:id', to: 'boards#toggle_visibility'

  resources :tasks, only: %i[show edit update destroy]
  get 'complete_task/:id', to: 'tasks#complete_task'
  post 'complete_task/:id', to: 'tasks#complete_task_action'

  resources :task_users, only: %i[create destroy]

  get 'admin', to: 'admins#admin_menu'

  resources :payments, only: %i[create new]

  resources :white_lists, only: [:index, :destroy, :create]
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="footer-top footer-section">
        <div class="container">
            <div class="d-flex align-items-center justify-content-center">
                <%= image_tag 'logo.png', alt: 'logo', class: 'logo' %>
                <h5>GreatBoard</h5>
            </div>
            <hr class="my-4">
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laboriosam nisi sint, fugit voluptatibus rerum rem distinctio suscipit, cupiditate tempora accusamus earum? Fuga voluptate perspiciatis officia reprehenderit maiores, cum quidem reiciendis!</p>
        </div>
    </div>

    <div class="footer-bottom footer-section">
        <div class="container">
            <p class="text-center m-0">© 2022 Copyright</p>
        </div>
    </div>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |type, msj| %>
  <div class="alert alert-<%= type == "notice" ? "success" : "danger" %> m-0 fade show" role="alert">
    <div class="d-flex justify-content-center">
      <span class="me-4"><%= msj %></span>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar bg-dark navbar-expand-lg navbar-dark">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
        <div class="d-flex align-items-center">
          <%= image_tag 'logo.png', alt: 'logo', class: 'logo' %>
          GreatBoard
        </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link #{nav_active_location_class(root_path)}" %>
        </li>
        <% if access_to_plan_page %>
          <li class="nav-item">
            <%= link_to 'Pricing', our_plans_path, class: "nav-link #{nav_active_location_class(our_plans_path)}" %>
          </li>
        <% end %>
        <% if user_logged? && !user_admin? %>
          <li class="nav-item">
            <%= link_to 'Boards', board_index_path(current_user), class: "nav-link #{nav_active_location_class(board_index_path(current_user))}" %>
          </li>
        <% end %>
        <% if user_admin?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Admin options
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><%= link_to 'Update plans', plans_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Admin page', '/admin', class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% end %>
        <% if user_logged? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li>
                  <%= link_to user_path(current_user), class: 'dropdown-item' do %>
                    <strong><%= current_user.first_name %></strong> 
                    <br>
                    <small><%= current_user.authorization_tier %></small>
                  <% end %>
              </li>
              <li><hr class="dropdown-divider"></li>
              <% if user_can_access_team_resources %>
                <li>
                    <%= link_to 'Teams', 
                                  user_teams_path(current_user), 
                                  class: 'dropdown-item' %>
                </li>
              <% end %>
              <li>
                <%= link_to 'Log out', 
                              destroy_user_session_path, 
                              class: 'dropdown-item',
                              method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
        <% if !user_logged?%>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: "nav-link #{nav_active_location_class(new_user_session_path)}" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreatBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="min-vh-100">
      <%= render 'layouts/message' %>
      <%= yield %>
    </div>

    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>